# Generated by Django 5.0.6 on 2026-04-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='🛒', help_text='Emoji yoki belgi', max_length=10, verbose_name='Ikonka')),
                ('color', models.CharField(default='#22c55e', help_text='Hex rang kodi', max_length=7, verbose_name='Rang')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'kg (kilogramm)'), ('g', 'g (gramm)'), ('dona', 'dona'), ('litr', 'litr'), ('boglam', "bog'lam"), ('tonna', 'tonna'), ('quti', 'quti')], default='kg', max_length=20, verbose_name="O'lchov birligi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('icon', models.CharField(blank=True, help_text="Rasm o'rniga emoji ishlatish (masalan 🍅)", max_length=10, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_seasonal', models.BooleanField(default=False, verbose_name='Mavsumiy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_popular', models.BooleanField(default=False, verbose_name="Mashhur (bosh sahifada ko'rsatish)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
