# Generated by Django 5.0.6 on 2026-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bozor nomi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Termiz uchun: 37.22 atrofida', max_digits=10, verbose_name='Kenglik (latitude)')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Termiz uchun: 67.27 atrofida', max_digits=10, verbose_name='Uzunlik (longitude)')),
                ('working_hours', models.CharField(default='06:00 - 19:00', max_length=100, verbose_name='Ish vaqti')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='markets/', verbose_name='Bozor rasmi')),
                ('color', models.CharField(default='#22c55e', help_text='Hex rang kodi (masalan #22c55e)', max_length=7, verbose_name='Bozor rangi (taqqoslash uchun)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bozor',
                'verbose_name_plural': 'Bozorlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
