# Generated by Django 5.0.6 on 2026-04-29 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='markets.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name': 'Narx tarixi',
                'verbose_name_plural': 'Narx tarixi',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Narx (so'm)")),
                ('date', models.DateField(verbose_name='Sana')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kiritilgan vaqt')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('quality', models.CharField(choices=[('high', 'Yuqori sifat'), ('medium', "O'rtacha"), ('low', 'Past')], default='medium', max_length=20, verbose_name='Sifati')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='markets.market', verbose_name='Bozor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Mahsulot')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_prices', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritgan')),
            ],
            options={
                'verbose_name': 'Narx',
                'verbose_name_plural': 'Narxlar',
                'ordering': ['-date', '-recorded_at'],
                'indexes': [models.Index(fields=['-date'], name='prices_pric_date_89585e_idx'), models.Index(fields=['product', 'market', '-date'], name='prices_pric_product_ec1cef_idx'), models.Index(fields=['market', '-date'], name='prices_pric_market__3dac54_idx')],
                'unique_together': {('product', 'market', 'date')},
            },
        ),
    ]
